require: rubocop-rails

# .rubocop.yml

# rubocop config files for Ruby 3.0 / Rails 6+ project

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'app/views/**/*'
    - 'db/**/*'

Bundler/OrderedGems:
  Enabled: false

Layout/LineLength:
  Max: 120

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'config/environments/*'
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Rails/DynamicFindBy:
  Enabled: false

Rails/HelperInstanceVariable:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
